---
- name: Apply Gateway API CRDs using kustomize output
  ansible.builtin.shell: |
    kubectl kustomize "{{ api_gtw_url }}" > /tmp/nginx-gateway-api-crds.yaml
  environment:
    KUBECONFIG: "{{ kube_config_file }}"

- name: Apply the Gateway API CRDs
  kubernetes.core.k8s:
    kubeconfig: "{{ kube_config_file }}"
    state: present
    src: /tmp/nginx-gateway-api-crds.yaml

- name: Apply the nginx-gateway-fabric CRDs
  kubernetes.core.k8s:
    kubeconfig: "{{ kube_config_file }}"
    state: present
    src: "{{ api_gtw_fabric_url }}"

- name: Deploy the nginx-gateway-fabric resources
  kubernetes.core.k8s:
    kubeconfig: "{{ kube_config_file }}"
    state: present
    src: "{{ api_gtw_deploy_url }}"
