---
- name: Create helm folder in controlplane server
  ansible.builtin.file:
    path: "{{ homelab_dir }}"
    state: directory
    mode: "0755"
    owner: ubuntu
    group: ubuntu

- name: copy app folders to remote
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ homelab_dir }}"
    mode: "0755"
    owner: ubuntu
    group: ubuntu
  loop:
    - linking-app.yaml
