apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sMinReplicaCount
metadata:
  name: deployment-must-have-min-replicas
spec:
  match:
    kinds:
      - apiGroups: ["apps"]
        kinds: ["Deployment"]
    excludedNamespaces:
      - default
      - kube-system
      - argocd
      - metallb-system
      - gatekeeper-system
      - kube-node-lease
      - kube-public
      - nginx-gateway
  parameters:
    min: 2
