---
- name: Install helm
  ansible.builtin.shell: |
    curl "{{ helm_url }}" | bash

- name: Download k9s .deb package
  ansible.builtin.shell: |
    curl -L -o k9s_linux_amd64.deb "{{ k9s_url }}"
  args:
    chdir: /tmp
    creates: /tmp/k9s_linux_amd64.deb

- name: Install k9s from downloaded .deb package
  ansible.builtin.apt:
    deb: /tmp/k9s_linux_amd64.deb

- name: Remove the k9s .deb file after installation
  ansible.builtin.file:
    path: /tmp/k9s_linux_amd64.deb
    state: absent

- name: Install python3-pip
  ansible.builtin.apt:
    name: python3-pip
    state: present
  become: true

- name: Install kubernetes python package
  ansible.builtin.pip:
    name: kubernetes
    executable: pip3
  become: true
